# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            奇门遁甲
tagline:          '唐三的博客'
url:              www.tang3.org
baseurl:  

author:           
  name:           '唐三'
  url:            http://www.tang3.org

paginate:         5

timezone:         Asia/Shanghai


# Plugins
gems:             [jekyll-paginate]


# Custom vars
safe:             false
